#!/bin/bash

echo ""
echo "--------------------------------------------------------------------------------"
echo "Deploying thomas-mcevoy.com with the following commit message:"
echo "'$1'"
echo "--------------------------------------------------------------------------------"

npm run build

git add .
git commit -m "$1"
git push

scp -r tom@68.183.30.7:~/thomas-mcevoy.com/. ./dist/
#ssh tom@68.183.30.7 "pm2 restart thomas-mcevoy.com"