#!/bin/bash

echo ""
echo "--------------------------------------------------------------------------------"
echo "Deploying thomas-mcevoy.com with the following commit message:"
echo "'$1'"
echo "--------------------------------------------------------------------------------"

npm run build

git add .
git commit -m "$1"
git push

ssh tom@68.183.30.7 <<'ENDSSH'
cd thomas-mcevoy.com
git pull
sudo rm -rf /var/www/html/*
sudo cp -r ./dist/* /var/www/html/
ENDSSH